### ISSUE TITLE
运行一段时间后无法发送消息

### ISSUE THREAD

**Issue by Dr-WeiAL** [touchscale/Qsign#1]
Qsign中重复出现了以下信息
```
[FEKit_]info: device_info.h:538 538
[FEKit_]info: device_info.h:540 540
[FEKit_]info: device_info.h:542 542
[FEKit_]info: device_token.h:235 begin pack
[FEKit_]info: device_token.h:237 pack buff result len:1412
[FEKit_]info: device_token.h:252 begin sendmessage : len :1412
[FEKit_]info: device_token.h:274 response len :0
[FEKit_]error: device_token.h:278 get token error! errorcode:999,mFailedTimes:2
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:MessageSvc.PbSendMsg
FEBound.transform(161401040000000002000300001c227c8981bebe5deac2f6d2d9e5da3628a817f9000000004865726f) => a85355f8a8520da7560dbb530d8fe233b3bb06553586702fb682c1ebfadbbbf083a752fda80deed54b
[FEKit_]error: device_info.h:178 jniGetAppVersionName:8.9.70
```
然后关闭Miao-Yunzai后Qsign出现了以下信息
```
16:46:56.076 [eventLoopGroupProxy-3-21] DEBUG ktor.application - I/O operation failed
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
16:46:56.076 [eventLoopGroupProxy-3-19] DEBUG ktor.application - I/O operation failed
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
16:46:56.076 [eventLoopGroupProxy-3-20] DEBUG ktor.application - I/O operation failed
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by touchscale** [comment]
使用的是哪个版本的api

**Comment by Dr-WeiAL** [comment]
> 使用的是哪个版本的api

根据Miao-Yunzai中的提示，调用的是8.9.70，使用的协议是aPad_8.9.70.11730

**Comment by touchscale** [comment]
> > 使用的是哪个版本的api
> 
> 根据Miao-Yunzai中的提示，调用的是8.9.70，使用的协议是aPad_8.9.70.11730

下载使用的是哪个版本的发行版，是1.2.1还是1.1.9

**Comment by Dr-WeiAL** [comment]
> > > 使用的是哪个版本的api
> > 
> > 
> > 根据Miao-Yunzai中的提示，调用的是8.9.70，使用的协议是aPad_8.9.70.11730
> 
> 下载使用的是哪个版本的发行版，是1.2.1还是1.1.9

直接克隆的本仓库，看了一下最后改动是9月27日

**Comment by touchscale** [comment]
> > > > 使用的是哪个版本的api
> > > 
> > > 
> > > 根据Miao-Yunzai中的提示，调用的是8.9.70，使用的协议是aPad_8.9.70.11730
> > 
> > 
> > 下载使用的是哪个版本的发行版，是1.2.1还是1.1.9
> 
> 直接克隆的本仓库，看了一下最后改动是9月27日

https://github.com/touchscale/Qsign/releases/tag/1.1.9

**Comment by touchscale** [comment]
> > > > 使用的是哪个版本的api
> > > 
> > > 
> > > 根据Miao-Yunzai中的提示，调用的是8.9.70，使用的协议是aPad_8.9.70.11730
> > 
> > 
> > 下载使用的是哪个版本的发行版，是1.2.1还是1.1.9
> 
> 直接克隆的本仓库，看了一下最后改动是9月27日

[1.1.9版本](https://github.com/touchscale/Qsign/releases/tag/1.1.9)，建议从发行版下载使用

**Comment by Dr-WeiAL** [comment]
好的我待会试试，如果没问题我就关闭这个吧

**Comment by touchscale** [comment]
> 好的我待会试试，如果没问题我就关闭这个吧

ok

**Comment by Dr-WeiAL** [comment]
目前为止没有出现问题了，应该是解决了
